eleData<-read.csv("household_power_consumption.txt", sep=";", colClasses = "character", header=T)
eleData1<-subset(eleData, eleData$Date== "1/2/2007")
eleData2<-subset(eleData, eleData$Date== "2/2/2007")
totalData<-rbind(eleData1, eleData2)
png(file="plot4.png", width = 480, height = 480)
par(mfrow=c(2, 2))
plot(as.numeric(as.character(totalData$Global_active_power)), type="l", ylab="Global Active Power", xaxt="n", xlab="")
axis(1, at=c(1,1440,2880), labels=c("Thu", "Fri", "Sat"), lwd=2)
axis(2, lwd=2)
plot(as.numeric(as.character(totalData$Voltage)), type="l", ylab="Voltage", xaxt="n", xlab="datetime")
axis(1, at=c(1,1440,2880), labels=c("Thu", "Fri", "Sat"), lwd=2)
axis(2, lwd=2)
plot(as.numeric(as.character(totalData$Sub_metering_1)), type="l", ylab="Energy Sub Metering", xaxt="n", xlab="", col="black")
lines(as.numeric(as.character(totalData$Sub_metering_2)), col="red")
lines(as.numeric(as.character(totalData$Sub_metering_3)), col="blue")
axis(1, at=c(1,1440,2880), labels=c("Thu", "Fri", "Sat"), lwd=2)
axis(2, lwd=2)
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty="n")
plot(as.numeric(as.character(totalData$Global_reactive_power)), type="l", ylab="Global_reactive_power", xaxt="n", xlab="datetime", lwd=-10)
axis(1, at=c(1,1440,2880), labels=c("Thu", "Fri", "Sat"), lwd=2)
axis(2, lwd=2)
dev.off()